[package]
name = "risczero-benchmark-methods"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
risc0-zkvm = { git = "https://github.com/risc0/risc0.git", default-features = false, features = [ "std" ] }
